### ISSUE TITLE
Example data

### ISSUE THREAD

**Issue by mk45** [mk45/road_project#2]
We need to create and add sample data into data/ directory. This must be simple line vector layer with up to 10 roads. Each road must have specified road class and (at least for now) width according to road class. Two attributes for each road, each of different type (class - string, width - kind of a number)

**Comment by mk45** [comment]
I wonder if it would be good to:
- change name drogi.shp -> roads.shp
- add column with size (at least for development we could have road size data directly)

**Comment by totczyk** [comment]
Done
